"""
Autonomous action layer for RootTrace.

Decides whether an incident diagnosis is confident enough to act on
autonomously, and -- only when explicitly enabled and gated by Step 3's
cross-verification result -- opens a real GitHub PR containing the incident
report and recommended fix.

Defaults to dry_run=True: without deliberate opt-in, no real GitHub write
ever happens, regardless of confidence. This "safe by default" design is
deliberate -- an autonomous system that can take real-world actions should
never do so by accident.

Scope note: this creates an incident-report PR (documenting the diagnosis
and recommended fix), not a literal code revert -- the mock incident data
doesn't reference a real revertible commit. The underlying GitHub
interaction (branch, commit, PR) is the same mechanism a true revert-PR
feature would use.
"""

import logging
from datetime import datetime, timezone

from github import Github, GithubException

from roottrace.config import settings
from roottrace.models import VerifiedDiagnosis, RemediationAction

logger = logging.getLogger(__name__)

CONFIDENCE_THRESHOLD = 70  # matches the threshold used in reasoning.py


class GitHubConfigMissing(RuntimeError):
    """Raised when a real GitHub action is attempted without GITHUB_TOKEN /
    GITHUB_REPO configured."""
    pass


def should_act_autonomously(diagnosis: VerifiedDiagnosis) -> tuple[bool, str]:
    """The actual safety gate. Returns (should_act, reason) so callers -- and
    logs -- always have a human-readable explanation for the decision, not
    just a bare boolean."""
    if diagnosis.requires_human_review:
        return False, "Models disagreed or confidence was below threshold during reasoning; human review required."
    if diagnosis.combined_confidence < CONFIDENCE_THRESHOLD:
        return False, f"Combined confidence {diagnosis.combined_confidence} is below the action threshold ({CONFIDENCE_THRESHOLD})."
    return True, f"Combined confidence {diagnosis.combined_confidence} meets the threshold and models agree."


def _build_report_markdown(diagnosis: VerifiedDiagnosis) -> str:
    return f"""# Incident Report (auto-generated by RootTrace)

**Generated:** {datetime.now(timezone.utc).isoformat()}
**Combined confidence:** {diagnosis.combined_confidence}%
**Models agree:** {diagnosis.models_agree}

## Root cause
{diagnosis.final_root_cause}

## Suggested fix
{diagnosis.llama_analysis.suggested_fix}

---
*This report was generated autonomously by RootTrace after cross-verifying
independent analyses from two models. Review before merging.*
"""


def take_action(diagnosis: VerifiedDiagnosis, dry_run: bool = True) -> RemediationAction:
    """The single entry point for the action layer. dry_run defaults to
    True -- see module docstring for why this default matters."""
    should_act, reason = should_act_autonomously(diagnosis)

    if not should_act:
        logger.warning("Action layer declined to act: %s", reason)
        return RemediationAction(action_taken=False, dry_run=dry_run, reason=reason)

    if dry_run:
        logger.info("DRY RUN: would open incident-report PR. Reason: %s", reason)
        return RemediationAction(
            action_taken=False,
            dry_run=True,
            reason=f"Dry run -- would have acted. {reason}",
        )

    if not settings.github_token or not settings.github_repo:
        raise GitHubConfigMissing("GITHUB_TOKEN and GITHUB_REPO must be set to take real action.")

    try:
        gh = Github(settings.github_token)
        repo = gh.get_repo(settings.github_repo)

        default_branch = repo.default_branch
        base_sha = repo.get_branch(default_branch).commit.sha
        branch_name = f"roottrace/incident-{int(datetime.now(timezone.utc).timestamp())}"
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)

        report_content = _build_report_markdown(diagnosis)
        repo.create_file(
            path=f"incident-reports/{branch_name.split('/')[-1]}.md",
            message="Add auto-generated incident report",
            content=report_content,
            branch=branch_name,
        )

        pr = repo.create_pull(
            title=f"[RootTrace] Incident: {diagnosis.final_root_cause[:60]}...",
            body=report_content,
            head=branch_name,
            base=default_branch,
        )

        logger.warning("Opened remediation PR: %s", pr.html_url)
        return RemediationAction(action_taken=True, dry_run=False, reason=reason, pr_url=pr.html_url)

    except GithubException as e:
        logger.exception("GitHub API error while taking action")
        raise